### ISSUE TITLE
Windowがちゃんと開かない

### ISSUE THREAD

**Issue by tatsuyatatsuya** [jmblog/qiita-notification-favicon#1]
Extentionを押した時に、Windowがちゃんと開かないことが最近増えました。こんな感じ：
![2015-04-28 21 08 45](https://cloud.githubusercontent.com/assets/6329239/7369200/e9fd7480-edea-11e4-94b6-72f935b4e4f6.png)

**Comment by jmblog** [comment]
@tatsuyatatsuya それは別の extension ですね。

https://github.com/ngs/qiita-notifications-crx
